### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lukeeey**

### CODE REVIEW

**Comment by SOF3** [comment]
Why?

**Comment by lukeeey** [comment]
Because it didnt display correctly (you need a space between the # and the text) and i added an extra # because i'm not familiar with the Poggit tabs thing and it seems to work for BlockHorizons

**Comment by SOF3** [comment]
But why add the first line?

**Comment by lukeeey** [comment]
Idk to provide a description i can remove it if you like

**Comment by Awzaw** [comment]
The read me has already been corrected in poggit for both versions of FactionsPro, and updated with all commands, I just didn't push changes to github yet

**Pull request closed without merging**
